name: My First Github Action

on: workflow_dispatch

jobs:
  send-a-message:
    runs-on: ubuntu-latest
    steps:
      - name: Watermelon HTTP client
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1.5
        with:
          url: 'tx.lese.rocks:8080'
          method: post
          data: '{"to": 1535487308, "message": "GitHub Actions message."}'
